server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: #{your-git-repository-url}
          clone-on-start: true
          # your git repository URL
          default-label: main
          username: #{your-git-username}
          # your git username
          password: #{your-git-password}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/