server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: # your git repository URL
          default-label: main
          username: # your git username


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/