server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chinthanachamod/Smart-Parking-MS.git
          clone-on-start: true
          # your git repository URL
          default-label: main
          username: chinthanachamod
          # your git username
          password: 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


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/